-- ============================================
-- Seed: All 32 provinces of Dominican Republic
-- ============================================
INSERT INTO provinces (name, zone) VALUES
  ('Distrito Nacional', 'Santo Domingo'),
  ('Santo Domingo', 'Santo Domingo'),
  ('Santo Domingo Este', 'Santo Domingo'),
  ('Santo Domingo Oeste', 'Santo Domingo'),
  ('Santo Domingo Norte', 'Santo Domingo'),
  ('Santiago', 'Cibao Norte'),
  ('Puerto Plata', 'Cibao Norte'),
  ('Espaillat', 'Cibao Norte'),
  ('La Vega', 'Cibao Central'),
  ('Monseñor Nouel', 'Cibao Central'),
  ('Sánchez Ramírez', 'Cibao Central'),
  ('Duarte', 'Cibao Nordeste'),
  ('María Trinidad Sánchez', 'Cibao Nordeste'),
  ('Hermanas Mirabal', 'Cibao Nordeste'),
  ('Samaná', 'Cibao Nordeste'),
  ('Valverde', 'Cibao Noroeste'),
  ('Monte Cristi', 'Cibao Noroeste'),
  ('Dajabón', 'Cibao Noroeste'),
  ('Santiago Rodríguez', 'Cibao Noroeste'),
  ('San Cristóbal', 'Valdesia'),
  ('Peravia', 'Valdesia'),
  ('San José de Ocoa', 'Valdesia'),
  ('Azua', 'El Valle'),
  ('San Juan', 'El Valle'),
  ('Elías Piña', 'El Valle'),
  ('Barahona', 'Enriquillo'),
  ('Bahoruco', 'Enriquillo'),
  ('Independencia', 'Enriquillo'),
  ('Pedernales', 'Enriquillo'),
  ('San Pedro de Macorís', 'Yuma'),
  ('La Romana', 'Yuma'),
  ('La Altagracia', 'Yuma'),
  ('El Seibo', 'Yuma'),
  ('Hato Mayor', 'Yuma'),
  ('Monte Plata', 'Ozama')
ON CONFLICT (name) DO NOTHING;
